### PR TITLE
String literal conversion to modifiable char*

### PR DESCRIPTION
**Pull request by Raesangur**
In files `English.h` and `French.h`, possible values for displayed text are saved like so:
```cpp
    constexpr char* TEXT_NEW_PROJECT_LAYER_WINDOW_NAME = "New Project";
```

This creates variables of type `char* const` instead of `const char* const` from a string literal, which is prohibited since ISO C++11.

Fix:
`constexpr const char* TEXT_NEW_PROJECT_LAYER_WINDOW_NAME = "New Project";`

### CODE REVIEW

**Comment by smartel99** [comment]
Does this cause any issues with the way they are currently being used in other files?

**Comment by Raesangur** [comment]
It doesn't cause issue (yet), but it's still illegal.
Im surprised there are no warnings with msvc (altough with clang it literally doesn't compile)

**Comment by smartel99** [comment]
I mean, does your fix work and compile?

**Comment by Raesangur** [comment]
yep

**Pull request merged**
